# Generated by Django 5.0.6 on 2024-06-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heroi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codinome', models.CharField(max_length=100)),
                ('poder', models.CharField(max_length=700)),
                ('profissao', models.CharField(max_length=200)),
                ('primeira_aparicao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vilao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codinome', models.CharField(max_length=100)),
                ('poder', models.CharField(max_length=700)),
                ('profissao', models.CharField(max_length=200)),
                ('primeira_aparicao', models.CharField(max_length=200)),
            ],
        ),
    ]
