# Generated by Django 5.0.6 on 2024-06-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_city', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroi',
            name='origem',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vilao',
            name='origem',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='heroi',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
